name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      run: |
        docker build -t pdf-extractor-backend backend/pdf-extractor-app/
        docker tag pdf-extractor-backend:latest ghcr.io/beastdev12/pdf-extractor/backend/pdf-extractor-app:latest
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u beastdev12 --password-stdin
        docker push ghcr.io/beastdev12/pdf-extractor/backend/pdf-extractor-app:latest

    - name: Deploy to GitHub Pages
      run: |
        docker run -d -p 80:5000 --name pdf-extractor-backend ghcr.io/beastdev12/pdf-extractor/backend/pdf-extractor-app:latest
